name: auto_test

# This action is triggered:
# 1. when someone creates a pull request for a merge to the main branch
# 2. when changes are merged into the main branch (via a pull request)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Below are jobs, each of which runs sequentially.
jobs:
  # This job builds the box model and runs our test suite.
  build:
    # A build matrix storing all desired configurations.
    strategy:
      matrix:
        os: [ubuntu-22.04] #, macos-latest]
        build-type: [Debug, Release]
        fp-precision: [single, double]

    runs-on: ${{ matrix.os }}

    # Environment variables
    env:
      CI: 1   # indicates that we are running in a CI environment.

    # Steps for building and running tests.
    steps:

    - name: Installing dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
        autoconf \
        clang-format \
        cmake \
        gcc \
        g++ \
        git \
        make \
        pkg-config \
        ca-certificates

    - name: Checking out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive

    - name: Configuring haero (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        ./setup build
        cd build
        cmake \
          -DCMAKE_INSTALL_PREFIX=`pwd`/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
          -DCMAKE_VERBOSE_MAKEFILE=ON \
          -DCMAKE_CXX_COMPILER=c++ \
          -DCMAKE_C_COMPILER=cc \
          -DHAERO_ENABLE_GPU=OFF \
          -DHAERO_ENABLE_OPENMP=ON \
          -DHAERO_ENABLE_MPI=OFF \
          -DHAERO_PRECISION=${{ matrix.fp-precision }} \
          -G "Unix Makefiles" \
          ..

    - name: Building haero (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        cd build
        make -j

    - name: Running tests (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        cd build
        ctest -V

    - name: Installing haero (${{ matrix.build-type }}, ${{ matrix.fp-precision }} precision)
      run: |
        cd build
        make install

